openapi: 3.0.0
info:
  description: Public API of the Yokoy Application
  title: Yokoy Card account Tax rates API
  version: 1.41.0
servers:
- description: API server scoped to organization with ID `organizationId`
  url: https://api.yokoy.ai/v1/organizations/{organizationId}
  variables:
    organizationId:
      default: AbcDeF1234
      description: Yokoy organization ID
- description: API test server scoped to organization with ID `organizationId`
  url: https://api.test.yokoy.ai/v1/organizations/{organizationId}
  variables:
    organizationId:
      default: AbcDeF1234
      description: Yokoy organization ID
tags:
- description: Tax rates. Tax rates apply to expenses, trips, and invoices. In Yokoy, you can consult them in **Admin > VAT / Tax rates**. For invoices, you can set up advanced tax components to adjust to complex tax scenarios. See [Set up advanced tax rates for invoices](https://help.yokoy.ai/en/articles/223727-set-up-advanced-tax-rates-for-invoices).
  name: Tax rates
paths:
  /legal-entities/{legalEntityId}/tax-rates:
    parameters:
    - $ref: '#/components/parameters/LegalEntityIdInPath'
    - $ref: '#/components/parameters/YokoyAuthMethod'
    - $ref: '#/components/parameters/YokoyCorrelationId'
    get:
      description: Retrieves all tax rates for the legal entity identified by its Yokoy unique ID in the path.
      operationId: listTaxRates
      parameters:
      - $ref: '#/components/parameters/QueryFilter'
      responses:
        '200':
          content:
            application/json:
              schema:
                example:
                - accountReference: 6300
                  code: tax77
                  country: CH
                  customInformation:
                    externalId: Tax77
                  name: Standard rate - CH
                  rate: 19
                  statusActive: true
                  validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                  version: one
                - accountReference: 6300
                  code: tax01
                  components:
                  - assessmentType: sellerAssessed
                    expenseAccount: GST-5
                    inputAccount: GST-5 IN
                    name: GST
                    outputAccount: GST-5 OUT
                    rate: 5
                    recoverablePercentage: 0
                  - assessmentType: sellerAssessed
                    expenseAccount: QST-9
                    inputAccount: QST-9 IN
                    name: QST
                    outputAccount: QST-9 OUT
                    rate: 9.975
                    recoverablePercentage: 0
                  country: CA
                  customInformation:
                    externalId: Tax1
                  id: 06x2u4nagAMEq3gGMoch
                  name: Standard rate - CA
                  rate: 14.975
                  statusActive: true
                  type: standard
                  validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                  version: two
                properties:
                  taxRates:
                    items:
                      anyOf:
                      - $ref: '#/components/schemas/TaxRate'
                      - $ref: '#/components/schemas/AdvancedTaxRate'
                    type: array
                type: object
          description: OK
        '400':
          $ref: '#/components/responses/InvalidFilter'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
        '502':
          $ref: '#/components/responses/GatewayError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      security:
      - OAuth2: []
      summary: List all tax rates
      tags:
      - Tax rates
    post:
      description: Creates a new tax rate and returns the created entity.
      operationId: createTaxRate
      requestBody:
        content:
          application/json:
            examples:
              AdvancedTaxRate:
                value:
                  accountReference: 6300
                  code: tax01
                  components:
                  - assessmentType: sellerAssessed
                    expenseAccount: GST-5
                    inputAccount: GST-5 IN
                    name: GST
                    outputAccount: GST-5 OUT
                    rate: 5
                    recoverablePercentage: 0
                  - assessmentType: sellerAssessed
                    inputAccount: QST-9 IN
                    name: QST
                    outputAccount: QST-9 OUT
                    rate: 9.975
                    recoverablePercentage: 0
                  country: CA
                  customInformation:
                    externalId: Tax1
                  expenseAccount: QST-9
                  name: Standard rate - CA
                  rate: 14.975
                  statusActive: true
                  type: standard
                  validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
              TaxRate:
                value:
                  accountReference: 6300
                  code: tax77
                  country: CH
                  customInformation:
                    externalId: Tax77
                  name: Standard rate - CH
                  rate: 19
                  statusActive: true
                  type: standard
                  validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
            schema:
              oneOf:
              - $ref: '#/components/schemas/TaxRate'
              - $ref: '#/components/schemas/AdvancedTaxRate'
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                AdvancedTaxRate:
                  value:
                    accountReference: 6300
                    code: tax01
                    components:
                    - assessmentType: sellerAssessed
                      expenseAccount: GST-5
                      inputAccount: GST-5 IN
                      name: GST
                      outputAccount: GST-5 OUT
                      rate: 5
                      recoverablePercentage: 0
                    - assessmentType: sellerAssessed
                      inputAccount: QST-9 IN
                      name: QST
                      outputAccount: QST-9 OUT
                      rate: 9.975
                      recoverablePercentage: 0
                    country: CA
                    customInformation:
                      externalId: Tax1
                    expenseAccount: QST-9
                    id: 06x2u4nagAMEq3gGMoch
                    name: Standard rate - CA
                    rate: 14.975
                    statusActive: true
                    type: standard
                    validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: two
                TaxRate:
                  value:
                    accountReference: 6300
                    code: tax77
                    country: CH
                    customInformation:
                      externalId: Tax77
                    id: 220ZSEO2l9
                    name: Standard rate - CH
                    rate: 19
                    statusActive: true
                    validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: one
              schema:
                oneOf:
                - $ref: '#/components/schemas/TaxRate'
                - $ref: '#/components/schemas/AdvancedTaxRate'
          description: Created
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
        '502':
          $ref: '#/components/responses/GatewayError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      security:
      - OAuth2: []
      summary: Create a tax rate
      tags:
      - Tax rates
  /legal-entities/{legalEntityId}/tax-rates/{taxRateId}:
    parameters:
    - $ref: '#/components/parameters/LegalEntityIdInPath'
    - description: Yokoy unique ID of the tax rate.
      example: 06x2u4nagAMEq3gGMoch
      in: path
      name: taxRateId
      required: true
      schema:
        pattern: '[\w-]+'
        type: string
    - $ref: '#/components/parameters/YokoyAuthMethod'
    - $ref: '#/components/parameters/YokoyCorrelationId'
    get:
      description: Retrieves a tax rate by its Yokoy unique ID.
      operationId: getTaxRate
      responses:
        '200':
          content:
            application/json:
              examples:
                AdvancedTaxRate:
                  value:
                    accountReference: 6300
                    code: tax01
                    components:
                    - assessmentType: sellerAssessed
                      expenseAccount: GST-5
                      inputAccount: GST-5 IN
                      name: GST
                      outputAccount: GST-5 OUT
                      rate: 5
                      recoverablePercentage: 0
                    - assessmentType: sellerAssessed
                      inputAccount: QST-9 IN
                      name: QST
                      outputAccount: QST-9 OUT
                      rate: 9.975
                      recoverablePercentage: 0
                    country: CA
                    customInformation:
                      externalId: Tax1
                    expenseAccount: QST-9
                    id: 06x2u4nagAMEq3gGMoch
                    name: Standard rate - CA
                    rate: 14.975
                    statusActive: true
                    type: standard
                    validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: two
                TaxRate:
                  value:
                    accountReference: 6300
                    code: tax77
                    country: CH
                    customInformation:
                      externalId: Tax77
                    id: 220ZSEO2l9
                    name: Standard rate - CH
                    rate: 19
                    statusActive: true
                    type: standard
                    validityEndDate: Mon, 01 Jan 2024 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: one
              schema:
                oneOf:
                - $ref: '#/components/schemas/TaxRate'
                - $ref: '#/components/schemas/AdvancedTaxRate'
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
        '502':
          $ref: '#/components/responses/GatewayError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      security:
      - OAuth2: []
      summary: Get a tax rate by ID
      tags:
      - Tax rates
    patch:
      description: Updates a tax rate by replacing some attributes. The legal entity and the tax rate are specified by their unique IDs in the path. The whole entity is returned.
      operationId: modifyTaxRate
      requestBody:
        content:
          application/json:
            examples:
              AdvancedTaxRate:
                value:
                  name: Standard rate - Updated description
              TaxRate:
                value:
                  name: Standard rate - Updated description
            schema:
              additionalProperties: true
              description: Dictionary of tax rate attributes to update. Explicit null values mark attributes for deletion.
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                AdvancedTaxRate:
                  value:
                    accountReference: 6300
                    code: tax01
                    components:
                    - assessmentType: sellerAssessed
                      expenseAccount: GST-5
                      inputAccount: GST-5 IN
                      name: GST
                      outputAccount: GST-5 OUT
                      rate: 5
                      recoverablePercentage: 0
                    - assessmentType: sellerAssessed
                      inputAccount: QST-9 IN
                      name: QST
                      outputAccount: QST-9 OUT
                      rate: 10
                      recoverablePercentage: 0
                    country: CA
                    customInformation: null
                    expenseAccount: QST-9
                    externalId: Tax1
                    id: 06x2u4nagAMEq3gGMoch
                    name: Standard rate - Updated description
                    rate: 15
                    statusActive: true
                    type: standard
                    validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: two
                TaxRate:
                  value:
                    accountReference: 6300
                    code: tax77
                    country: CH
                    customInformation:
                      externalId: Tax77
                    id: 220ZSEO2l9
                    name: Standard rate - Updated description
                    rate: 19
                    statusActive: true
                    validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: one
              schema:
                oneOf:
                - $ref: '#/components/schemas/TaxRate'
                - $ref: '#/components/schemas/AdvancedTaxRate'
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
        '502':
          $ref: '#/components/responses/GatewayError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      security:
      - OAuth2: []
      summary: Modify a tax rate
      tags:
      - Tax rates
    put:
      description: Updates a tax rate identified by replacing all attributes. The legal entity and the tax rate are specified by their unique IDs in the path. Any attributes that are not specified in the request body are updated with null or "" and is flagged as inactive. The whole entity is returned.
      operationId: updateTaxRate
      requestBody:
        content:
          application/json:
            examples:
              AdvancedTaxRate:
                value:
                  accountReference: 6300
                  code: tax01
                  components:
                  - assessmentType: sellerAssessed
                    expenseAccount: GST-5
                    inputAccount: GST-5 IN
                    name: GST
                    outputAccount: GST-5 OUT
                    rate: 5
                    recoverablePercentage: 0
                  - assessmentType: sellerAssessed
                    inputAccount: QST-9 IN
                    name: QST
                    outputAccount: QST-9 OUT
                    rate: 10
                    recoverablePercentage: 0
                  country: CA
                  customInformation: null
                  expenseAccount: QST-9
                  externalId: Tax1
                  id: 06x2u4nagAMEq3gGMoch
                  name: Standard rate - CA 2025
                  rate: 15
                  statusActive: true
                  type: standard
                  validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                  version: two
              TaxRate:
                value:
                  accountReference: 6300
                  code: tax77
                  country: CH
                  customInformation:
                    externalId: Tax77
                  id: 220ZSEO2l9
                  name: Standard rate - CH 2025
                  rate: 19
                  statusActive: true
                  validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                  validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                  version: one
            schema:
              oneOf:
              - $ref: '#/components/schemas/TaxRate'
              - $ref: '#/components/schemas/AdvancedTaxRate'
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                AdvancedTaxRate:
                  value:
                    accountReference: 6300
                    code: tax01
                    components:
                    - assessmentType: sellerAssessed
                      expenseAccount: GST-5
                      inputAccount: GST-5 IN
                      name: GST
                      outputAccount: GST-5 OUT
                      rate: 5
                      recoverablePercentage: 0
                    - assessmentType: sellerAssessed
                      inputAccount: QST-9 IN
                      name: QST
                      outputAccount: QST-9 OUT
                      rate: 10
                      recoverablePercentage: 0
                    country: CA
                    customInformation: null
                    expenseAccount: QST-9
                    externalId: Tax1
                    id: 06x2u4nagAMEq3gGMoch
                    name: Standard rate - CA 2025
                    rate: 15
                    statusActive: true
                    type: standard
                    validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: two
                TaxRate:
                  value:
                    accountReference: 6300
                    code: tax77
                    country: CH
                    customInformation:
                      externalId: Tax77
                    id: 220ZSEO2l9
                    name: Standard rate - CH 2025
                    rate: 19
                    statusActive: true
                    validityEndDate: Wed, 01 Jan 2025 00:00:00 GMT
                    validityStartDate: Wed, 01 Jan 2020 00:00:00 GMT
                    version: one
              schema:
                oneOf:
                - $ref: '#/components/schemas/TaxRate'
                - $ref: '#/components/schemas/AdvancedTaxRate'
          description: OK
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
        '502':
          $ref: '#/components/responses/GatewayError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      security:
      - OAuth2: []
      summary: Update a tax rate
      tags:
      - Tax rates
components:
  schemas:
    TaxComponents:
      description: Advanced tax configuration has to be enabled for the legal entity to use tax rate components. Applicable only for invoices. If tax components are present, tax rate version is set to `two` internally.
      properties:
        assessmentType:
          description: Whether the tax component is self-assessed or seller-assessed.
          enum:
          - selfAssessed
          - sellerAssessed
          example: sellerAssessed
          nullable: false
          type: string
        expenseAccount:
          description: Expense account to be used to post the tax component.
          example: GST-5
          type: string
        inputAccount:
          description: Input account for the tax component
          example: GST-5 IN
          type: string
        name:
          description: Name of the tax rate component.
          example: GST
          type: string
        outputAccount:
          description: The output account for the tax component
          example: GST-5 OUT
          type: string
        rate:
          description: Rate of the tax component.
          example: 5
          nullable: true
          type: number
        recoverablePercentage:
          description: Recoverable percentage of the tax component. 100 is interpreted as 100%
          example: 0
          type: number
      required:
      - name
      - rate
      - recoverablePercentage
      - assessmentType
      type: object
    DateString:
      example: '2024-02-21'
      format: date
      pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
      type: string
    AdvancedTaxRate:
      allOf:
      - $ref: '#/components/schemas/TaxRate'
      properties:
        components:
          allOf:
          - $ref: '#/components/schemas/TaxComponents'
          nullable: false
      required:
      - components
      type: object
    Error:
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    TaxRate:
      properties:
        accountReference:
          description: Account (ERP) associated with the tax rate. Relevant for posting bookings.
          example: 6300
          type: string
        code:
          description: Code (ERP). External reference of the tax rate.
          example: tax77
          type: string
        country:
          description: Country of the tax rate. Expressed as an ISO 3166 Alpha-2 code.
          example: CH
          type: string
        customInformation:
          additionalProperties:
            type: string
          description: Dictionary of custom information attributes associated with the tax rate.
          example:
            externalId: Tax1
          nullable: true
          type: object
        id:
          description: Yokoy unique ID of the tax rate.
          example: 06x2u4nagAMEq3gGMoch
          pattern: '[\w-]+'
          readOnly: true
          type: string
        name:
          description: Name of the tax rate.
          example: Standard rate
          type: string
        rate:
          description: Tax rate in percentage. Used to match tax rate when digitizing expenses. Accepts numbers up to 15 decimal places.
          example: 19
          type: number
        statusActive:
          description: Status of the tax rate. Only active rates are considered in expenses and invoices.
          example: true
          type: boolean
        type:
          description: Category that classifies the tax rate. Used to determine the tax rate in e-invoices.
          enum:
          - standard
          - reduced
          - specialReduced
          - zero
          - exempt
          - domesticReverseCharge
          example: standard
          nullable: false
          type: string
        validityEndDate:
          allOf:
          - $ref: '#/components/schemas/DateString'
          - description: Validity end date for the tax rate.
            example: '2024-01-01'
            nullable: true
        validityStartDate:
          allOf:
          - $ref: '#/components/schemas/DateString'
          - description: Validity start date for the tax rate.
            example: '2020-01-01'
            nullable: true
        version:
          description: Applicable only for invoices. Version set to `two` internally if tax rate has components; otherwise `one`. If no version is present, the version is considered to be `one`.
          enum:
          - one
          - two
          nullable: false
          readOnly: true
          type: string
      required:
      - name
      - code
      - accountReference
      - rate
      - country
      - statusActive
      type: object
  parameters:
    QueryFilter:
      description: Filter string used to restrict the data returned. You can use [SCIM specification](https://tools.ietf.org/html/rfc7644#section-3.4.2.2) filters.
      example: created ge 2024-03-02T09:00.000Z and customInformation.customField eq foo
      in: query
      name: filter
      schema:
        type: string
    YokoyAuthMethod:
      example: yokoy
      in: header
      name: X-Yk-Auth-Method
      required: true
      schema:
        enum:
        - yokoy
        type: string
    YokoyCorrelationId:
      description: Correlation ID that can be used to trace a request in the flow.
      example: 4ea8985e-80a2-40a0-8a40-401a1a1374b3
      in: header
      name: X-Yk-Correlation-Id
      required: false
      schema:
        type: string
    LegalEntityIdInPath:
      description: Yokoy unique ID of the legal entity (company).
      example: aB9jQoE3HE
      in: path
      name: legalEntityId
      required: true
      schema:
        pattern: '[\w-]+'
        type: string
  responses:
    Forbidden:
      content:
        application/json:
          example:
            code: 403
            message: User not authorized to access organization
          schema:
            $ref: '#/components/schemas/Error'
      description: The client is not authorized to perform the requested operation.
    Unauthorized:
      content:
        application/json:
          example:
            code: 401
            message: Token expired
          schema:
            $ref: '#/components/schemas/Error'
      description: The server was unable to establish the identity of the client.
    ValidationError:
      content:
        application/json:
          example:
            code: 400
            message: 'ValidationError: name is mandatory'
          schema:
            $ref: '#/components/schemas/Error'
      description: The request was not valid.
    InvalidFilter:
      content:
        application/json:
          example:
            code: 400
            message: 'Invalid filter string: foo e bar'
          schema:
            $ref: '#/components/schemas/Error'
      description: The request was not valid.
    TooManyRequests:
      content:
        application/json:
          example:
            code: 429
            message: Too many requests
          schema:
            $ref: '#/components/schemas/Error'
      description: The request cannot be processed by the server due to too many concurrent requests.
    InternalError:
      content:
        application/json:
          example:
            code: 500
            message: Server error
          schema:
            $ref: '#/components/schemas/Error'
      description: An internal error occurred.
    NotFound:
      content:
        application/json:
          example:
            code: 404
            message: Resource not found
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found.
    GatewayError:
      content:
        application/json:
          example:
            code: 502
            message: Gateway error
          schema:
            $ref: '#/components/schemas/Error'
      description: An issue occurred in a downstream service. Please try again later.
    ServiceUnavailable:
      content:
        application/json:
          example:
            code: 503
            message: Service unavailable
          schema:
            $ref: '#/components/schemas/Error'
      description: The server is unavailable. Please try again later
  securitySchemes:
    OAuth2:
      description: "Authentication to the Yokoy API relies on the standard OAuth2 client credentials flow.\n\n**1. Obtain an access token**\n\nPerform a `POST` request to\n`https://accounts.yokoy.ai/oauth2/token`. Pass the client ID\nand client secret as username and password in a basic auth\nheader. Set the content-type to\n`application/x-www-form-urlencoded` and specify\n`grant_type=client_credentials` in the body.\n\n> Note: For the Yokoy test environment, use `https://accounts.test.yokoy.ai/oauth2/token` instead.\n\nExample request for the client ID `ClientId` and client\nsecret `ClientSecret`:\n```\nPOST https://accounts.yokoy.ai/oauth2/token\nAuthorization: Basic Q2xpZW50SWQ6Q2xpZW50U2VjcmV0\nContent-Type: application/x-www-form-urlencoded\ngrant_type=client_credentials\n```\nIn this example, the string `Q2xpZW50SWQ6Q2xpZW50U2VjcmV0` is\nobtained by base64-encoding the string\n`ClientId:ClientSecret`, as required for basic access authentication.\n\n> Note: Yokoy does not require or use scopes.\n\n\nThe JSON response contains the access token in the attribute\n`access_token`. The response also contains the expiration in\nseconds.\n\nExample response:\n```\n{\n    \"access_token\": \"SOME_KEY\",\n    \"expires_in\": 3900,\n    \"token_type\": \"Bearer\"\n}\n```\n\n**2. Pass the bearer token**\n\nPass the access token from step 1 as a bearer token in subsequent requests to the API.\n\nExample header field for the example response from step 1:\n```\nAuthorization: Bearer 4lDvPkrBF87WHuyvlINQD\n```\n\nFor more information, see (Authentication & authorization)[https://developer.yokoy.ai/docs/overview/authentication].\n"
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://accounts[.test].yokoy.ai/oauth2/token
      type: oauth2
